<template><div><nav class="table-of-contents"><ul><li><router-link to="#_13-字典「dict-dannie」">13-字典「dict/Dannie」</router-link></li><li><router-link to="#_1-请使用之前的知识做出一个简易的电话本">1. 请使用之前的知识做出一个简易的电话本</router-link></li><li><router-link to="#电话本方法二">电话本方法二</router-link></li><li><router-link to="#字典的结构">字典的结构</router-link></li><li><router-link to="#字典结构—key">字典结构—key</router-link></li><li><router-link to="#用字典-dict-函数创建字典">用字典 dict 函数创建字典</router-link></li><li><router-link to="#字典提取数据">字典提取数据</router-link></li><li><router-link to="#get">get()</router-link></li><li><router-link to="#更新字典数据「update-dict-data」">更新字典数据「update dict data」</router-link></li><li><router-link to="#字典的删除「del」">字典的删除「del」</router-link></li><li><router-link to="#字典嵌套">字典嵌套</router-link></li><li><router-link to="#字典放在列表内">字典放在列表内</router-link></li><li><router-link to="#字典嵌套列表">字典嵌套列表</router-link></li></ul></nav>
<h2 id="_13-字典「dict-dannie」" tabindex="-1"><a class="header-anchor" href="#_13-字典「dict-dannie」" aria-hidden="true">#</a> 13-字典「dict/Dannie」</h2>
<h2 id="_1-请使用之前的知识做出一个简易的电话本" tabindex="-1"><a class="header-anchor" href="#_1-请使用之前的知识做出一个简易的电话本" aria-hidden="true">#</a> 1. 请使用之前的知识做出一个简易的电话本</h2>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>name_lst <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">"aiyc"</span><span class="token punctuation">,</span> <span class="token string">"dannie"</span><span class="token punctuation">,</span> <span class="token string">"jaden"</span><span class="token punctuation">]</span>
number_lst <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">"123"</span><span class="token punctuation">,</span> <span class="token string">"456"</span><span class="token punctuation">,</span> <span class="token string">"789"</span><span class="token punctuation">]</span>
username <span class="token operator">=</span> <span class="token builtin">input</span><span class="token punctuation">(</span><span class="token string">"我让你输入一个值，这个值是你要查找的用户名称，你输入的值，将会赋值给 username："</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"username 的值是:"</span><span class="token punctuation">,</span> username<span class="token punctuation">)</span>
xiabiao <span class="token operator">=</span> name_lst<span class="token punctuation">.</span>index<span class="token punctuation">(</span>username<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>xiabiao<span class="token punctuation">)</span>
number <span class="token operator">=</span> number_lst<span class="token punctuation">[</span>xiabiao<span class="token punctuation">]</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>number<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>name<span class="token operator">=</span><span class="token punctuation">[</span><span class="token string">"Lyon"</span><span class="token punctuation">,</span> <span class="token string">"Dannie"</span><span class="token punctuation">,</span> <span class="token string">"Curtis"</span><span class="token punctuation">,</span> <span class="token string">"Mason"</span><span class="token punctuation">]</span>
fruit<span class="token operator">=</span><span class="token punctuation">[</span><span class="token string">"Grape"</span><span class="token punctuation">,</span> <span class="token string">"Watermelon"</span><span class="token punctuation">,</span> <span class="token string">"Orange"</span><span class="token punctuation">,</span> <span class="token string">"kiwi"</span><span class="token punctuation">]</span>

key_in<span class="token operator">=</span><span class="token builtin">input</span><span class="token punctuation">(</span><span class="token string">"Please key in family's name:"</span> <span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>key_in<span class="token punctuation">)</span>

location<span class="token operator">=</span>name<span class="token punctuation">.</span>index<span class="token punctuation">(</span>key_in<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>location<span class="token punctuation">)</span>

print_out<span class="token operator">=</span>fruit<span class="token punctuation">[</span>location<span class="token punctuation">]</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"His/Her favorite fruit is:"</span><span class="token punctuation">,</span>print_out<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/1v1/03-Dannie/13.assets/image-20221101002338557.png" alt="image-20221101002338557" loading="lazy"></p>
<hr>
<h2 id="电话本方法二" tabindex="-1"><a class="header-anchor" href="#电话本方法二" aria-hidden="true">#</a> 电话本方法二</h2>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>phone_lst<span class="token operator">=</span><span class="token punctuation">[</span><span class="token string">"aicy"</span><span class="token punctuation">,</span><span class="token string">"123"</span><span class="token punctuation">,</span><span class="token string">"dannie"</span><span class="token punctuation">,</span><span class="token string">"456"</span><span class="token punctuation">,</span><span class="token string">"jaden"</span><span class="token punctuation">,</span><span class="token string">"789"</span><span class="token punctuation">]</span>
i<span class="token operator">=</span><span class="token builtin">input</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
o<span class="token operator">=</span>phone_lst<span class="token punctuation">.</span>index<span class="token punctuation">(</span>i<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>phone_lst<span class="token punctuation">[</span>o<span class="token operator">+</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>输出：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>输入： jaden
输出：<span class="token number">789</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>phone_lst<span class="token operator">=</span><span class="token punctuation">[</span><span class="token string">"aicy"</span><span class="token punctuation">,</span><span class="token string">"123"</span><span class="token punctuation">,</span><span class="token string">"dannie"</span><span class="token punctuation">,</span><span class="token string">"456"</span><span class="token punctuation">,</span><span class="token string">"jaden"</span><span class="token punctuation">,</span><span class="token string">"789"</span><span class="token punctuation">]</span>
i<span class="token operator">=</span><span class="token builtin">input</span><span class="token punctuation">(</span><span class="token string">"Please key in the name: "</span> <span class="token punctuation">,</span> <span class="token punctuation">)</span>
o<span class="token operator">=</span>phone_lst<span class="token punctuation">.</span>index<span class="token punctuation">(</span>i<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"phone number is: "</span><span class="token punctuation">,</span>  phone_lst<span class="token punctuation">[</span>o<span class="token operator">+</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>输出：</p>
<p><img src="@source/1v1/03-Dannie/13.assets/image-20221101213853233.png" alt="image-20221101213853233" loading="lazy"></p>
<blockquote>
<p>input 有时候要写输入提示哦，不然运行起来有时候自己都会蒙的。</p>
</blockquote>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>phone_lst<span class="token operator">=</span><span class="token punctuation">[</span><span class="token string">"aicy"</span><span class="token punctuation">,</span><span class="token string">"123"</span><span class="token punctuation">,</span><span class="token string">"dannie"</span><span class="token punctuation">,</span><span class="token string">"456"</span><span class="token punctuation">,</span><span class="token string">"jaden"</span><span class="token punctuation">,</span><span class="token string">"789"</span><span class="token punctuation">]</span>
i<span class="token operator">=</span><span class="token builtin">input</span><span class="token punctuation">(</span><span class="token string">"Please key in the name: "</span> <span class="token punctuation">,</span> <span class="token punctuation">)</span>
o<span class="token operator">=</span>phone_lst<span class="token punctuation">.</span>index<span class="token punctuation">(</span>i<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"phone number is: "</span><span class="token punctuation">,</span>  phone_lst<span class="token punctuation">[</span>o<span class="token operator">+</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span>

<span class="token keyword">print</span><span class="token punctuation">(</span>phone_lst<span class="token punctuation">[</span>phone_lst<span class="token punctuation">.</span>index<span class="token punctuation">(</span><span class="token builtin">input</span><span class="token punctuation">(</span><span class="token string">"please key in the name:"</span><span class="token punctuation">,</span> <span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token operator">+</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>输出：</p>
<p><img src="@source/1v1/03-Dannie/13.assets/image-20221101214526356.png" alt="image-20221101214526356" loading="lazy"></p>
<blockquote>
<p>该一行的时候一行，不该一行写完代码的时候，不要那么写。——可读性较低</p>
</blockquote>
<h2 id="字典的结构" tabindex="-1"><a class="header-anchor" href="#字典的结构" aria-hidden="true">#</a> 字典的结构</h2>
<p><img src="@source/1v1/03-Dannie/13.assets/image-20221101214739233.png" alt="image-20221101214739233" loading="lazy"></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>phone_lst<span class="token operator">=</span><span class="token punctuation">{</span><span class="token string">"aicy"</span><span class="token punctuation">:</span><span class="token string">"123"</span><span class="token punctuation">,</span><span class="token string">"dannie"</span><span class="token punctuation">:</span><span class="token string">"456"</span><span class="token punctuation">,</span><span class="token string">"jaden"</span><span class="token punctuation">:</span><span class="token string">"789"</span><span class="token punctuation">}</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token builtin">type</span><span class="token punctuation">(</span>phone_lst<span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>key：不可变「不可以使用可变的数据类型，当作字典的 key」list：可以做 key 吗？——不可以，因为，列表可变</li>
<li>数字型可以做 key 吗？——可以，数字不可变</li>
<li>元组「tuple」可以做 key 吗？——可以，元组不可变</li>
<li>字符串「str」可以做 key 吗？——可以，字符串不可变</li>
<li>集合「set」可以做 key 吗？——不可以，集合可变</li>
<li>布尔型「bool」可以做 key 吗？——可以，bool 不可变</li>
<li>value：任意数据类型</li>
</ul>
<h2 id="字典结构—key" tabindex="-1"><a class="header-anchor" href="#字典结构—key" aria-hidden="true">#</a> 字典结构—key</h2>
<p><img src="@source/1v1/03-Dannie/13.assets/image-20221101215552539.png" alt="image-20221101215552539" loading="lazy"></p>
<h2 id="用字典-dict-函数创建字典" tabindex="-1"><a class="header-anchor" href="#用字典-dict-函数创建字典" aria-hidden="true">#</a> 用字典 dict 函数创建字典</h2>
<p><img src="@source/1v1/03-Dannie/13.assets/image-20221101215921522.png" alt="image-20221101215921522" loading="lazy"></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>phone_lst<span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string">"aiyc"</span><span class="token punctuation">]</span><span class="token punctuation">,</span><span class="token string">"123"</span><span class="token punctuation">)</span><span class="token punctuation">,</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string">"jaden"</span><span class="token punctuation">]</span><span class="token punctuation">,</span><span class="token string">"789"</span><span class="token punctuation">)</span><span class="token punctuation">]</span>
phone_lst_new <span class="token operator">=</span> <span class="token builtin">dict</span><span class="token punctuation">(</span>phone_lst<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>phone_lst_new<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>输出：</p>
<p><img src="@source/1v1/03-Dannie/13.assets/image-20221101220844862.png" alt="image-20221101220844862" loading="lazy"></p>
<p>输出会有报错， 因为字典里面的元组，第一个不能是列表。</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>d <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">(</span><span class="token string">"aiyc"</span><span class="token punctuation">,</span> <span class="token string">"value"</span><span class="token punctuation">)</span><span class="token punctuation">,</span><span class="token punctuation">(</span><span class="token string">"Aiyc"</span><span class="token punctuation">,</span> <span class="token string">"look"</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token number">123</span><span class="token punctuation">,</span> <span class="token number">223</span><span class="token punctuation">)</span><span class="token punctuation">]</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token builtin">dict</span><span class="token punctuation">(</span>d<span class="token punctuation">)</span><span class="token punctuation">)</span>

d<span class="token operator">=</span><span class="token builtin">dict</span><span class="token punctuation">(</span> name <span class="token operator">=</span><span class="token string">"aiyc"</span><span class="token punctuation">,</span> age <span class="token operator">=</span> <span class="token number">19</span> <span class="token punctuation">)</span>
<span class="token keyword">print</span> <span class="token punctuation">(</span>d<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><blockquote>
<p>第一种写法： key, 可以不一定全部都要求是字符串， 例子里面 123 数值也做了 key</p>
<p>第二种的写法不能够支持全部的类型（可以做字典 key 的类型）</p>
<p>第二种写法， 赋值式的， 但是 key 基本上也被规定了相同的类型，比如 字符串， 后面的 age 也是字符串</p>
</blockquote>
<h2 id="字典提取数据" tabindex="-1"><a class="header-anchor" href="#字典提取数据" aria-hidden="true">#</a> 字典提取数据</h2>
<p><img src="@source/1v1/03-Dannie/13.assets/image-20221104212023156.png" alt="image-20221104212023156" loading="lazy"></p>
<h2 id="get" tabindex="-1"><a class="header-anchor" href="#get" aria-hidden="true">#</a> get()</h2>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>d <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">"name"</span><span class="token punctuation">:</span> <span class="token string">"aiyc"</span><span class="token punctuation">,</span> <span class="token string">"age"</span><span class="token punctuation">:</span> <span class="token string">"18"</span><span class="token punctuation">}</span>
<span class="token comment"># print(d["name1"])</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>d<span class="token punctuation">.</span>get<span class="token punctuation">(</span><span class="token string">"name"</span><span class="token punctuation">)</span><span class="token punctuation">)</span>  <span class="token comment"># 如果 key 存在则返回值，否则默认返回 none</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>d<span class="token punctuation">.</span>get<span class="token punctuation">(</span><span class="token string">"namesssss"</span><span class="token punctuation">)</span><span class="token punctuation">)</span>  <span class="token comment"># 如果 key 存在则返回值，否则默认返回 None</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>d<span class="token punctuation">.</span>get<span class="token punctuation">(</span><span class="token string">"namesssss"</span><span class="token punctuation">,</span> <span class="token string">"小主，我没有找到哦～"</span><span class="token punctuation">)</span><span class="token punctuation">)</span>  <span class="token comment"># 如果 key 存在则返回值，否则默认返回 None</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>输出：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>aiyc
<span class="token boolean">None</span>
小主，我没有找到哦～
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>grade <span class="token operator">=</span> <span class="token punctuation">{</span> <span class="token string">"lilei"</span><span class="token punctuation">:</span><span class="token string">"98"</span><span class="token punctuation">,</span> <span class="token string">"hanmeimei"</span><span class="token punctuation">:</span> <span class="token string">"99"</span><span class="token punctuation">}</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>grade<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>grade<span class="token punctuation">.</span>get<span class="token punctuation">(</span><span class="token string">"dannie"</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>grade<span class="token punctuation">.</span>get<span class="token punctuation">(</span><span class="token string">"dannie"</span><span class="token punctuation">,</span> <span class="token string">"it is not exist, try again"</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>输出：</p>
<p><img src="@source/1v1/03-Dannie/13.assets/image-20221104213709025.png" alt="image-20221104213709025" loading="lazy"></p>
<h2 id="更新字典数据「update-dict-data」" tabindex="-1"><a class="header-anchor" href="#更新字典数据「update-dict-data」" aria-hidden="true">#</a> 更新字典数据「update dict data」</h2>
<p><img src="@source/1v1/03-Dannie/13.assets/image-20221104213825717.png" alt="image-20221104213825717" loading="lazy"></p>
<h2 id="字典的删除「del」" tabindex="-1"><a class="header-anchor" href="#字典的删除「del」" aria-hidden="true">#</a> 字典的删除「del」</h2>
<p><img src="@source/1v1/03-Dannie/13.assets/image-20221104214803423.png" alt="image-20221104214803423" loading="lazy"></p>
<h2 id="字典嵌套" tabindex="-1"><a class="header-anchor" href="#字典嵌套" aria-hidden="true">#</a> 字典嵌套</h2>
<p><img src="@source/1v1/03-Dannie/13.assets/image-20221104215214028.png" alt="image-20221104215214028" loading="lazy"></p>
<h2 id="字典放在列表内" tabindex="-1"><a class="header-anchor" href="#字典放在列表内" aria-hidden="true">#</a> 字典放在列表内</h2>
<p><img src="@source/1v1/03-Dannie/13.assets/image-20221107213846947.png" alt="image-20221107213846947" loading="lazy"></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>favorite_class<span class="token operator">=</span><span class="token punctuation">{</span><span class="token string">'lilei'</span><span class="token punctuation">:</span><span class="token punctuation">[</span><span class="token string">'Math'</span><span class="token punctuation">,</span> <span class="token string">'English'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token string">'hanmeimei'</span><span class="token punctuation">:</span><span class="token punctuation">[</span><span class="token string">'Chinese'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token string">'madongmei'</span><span class="token punctuation">:</span><span class="token punctuation">[</span><span class="token string">'Computer'</span><span class="token punctuation">,</span><span class="token string">'Physic'</span><span class="token punctuation">,</span> <span class="token string">'Math'</span><span class="token punctuation">]</span><span class="token punctuation">}</span>
class2 <span class="token operator">=</span> favorite_class <span class="token punctuation">[</span><span class="token string">'lilei'</span><span class="token punctuation">]</span>
<span class="token keyword">print</span> <span class="token punctuation">(</span>class2<span class="token punctuation">)</span>
<span class="token keyword">print</span> <span class="token punctuation">(</span>class2<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span>

class3<span class="token operator">=</span>favorite_class<span class="token punctuation">[</span><span class="token string">'madongmei'</span><span class="token punctuation">]</span>
<span class="token keyword">print</span> <span class="token punctuation">(</span>class3<span class="token punctuation">)</span>
<span class="token keyword">print</span> <span class="token punctuation">(</span>class3<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span>

<span class="token keyword">print</span> <span class="token punctuation">(</span>favorite_class <span class="token punctuation">[</span><span class="token string">'lilei'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">,</span> favorite_class <span class="token punctuation">[</span><span class="token string">'madongmei'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">,</span> sep<span class="token operator">=</span> <span class="token string">','</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="@source/1v1/03-Dannie/13.assets/image-20221107214102590.png" alt="image-20221107214102590" loading="lazy"></p>
<h2 id="字典嵌套列表" tabindex="-1"><a class="header-anchor" href="#字典嵌套列表" aria-hidden="true">#</a> 字典嵌套列表</h2>
<p><img src="@source/1v1/03-Dannie/13.assets/image-20221107213949392.png" alt="image-20221107213949392" loading="lazy"></p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code>student1<span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'name'</span><span class="token punctuation">:</span> <span class="token string">'lilei'</span><span class="token punctuation">,</span> <span class="token string">'score'</span><span class="token punctuation">:</span> <span class="token string">'98'</span><span class="token punctuation">,</span> <span class="token string">'testing_class'</span><span class="token punctuation">:</span> <span class="token boolean">True</span><span class="token punctuation">}</span>
class1 <span class="token operator">=</span><span class="token punctuation">{</span>
    <span class="token string">'lilei'</span><span class="token punctuation">:</span><span class="token punctuation">{</span><span class="token string">'score'</span><span class="token punctuation">:</span><span class="token string">'98'</span><span class="token punctuation">,</span> <span class="token string">'testing_class'</span><span class="token punctuation">:</span> <span class="token boolean">True</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token string">'hanmeimei'</span><span class="token punctuation">:</span> <span class="token punctuation">{</span><span class="token string">'score'</span><span class="token punctuation">:</span><span class="token string">'95'</span><span class="token punctuation">,</span> <span class="token string">'testing_class'</span><span class="token punctuation">:</span> <span class="token boolean">False</span><span class="token punctuation">}</span>
<span class="token punctuation">}</span>

p1<span class="token operator">=</span>class1<span class="token punctuation">[</span><span class="token string">'lilei'</span><span class="token punctuation">]</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p1<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p1<span class="token punctuation">[</span><span class="token string">'testing_class'</span><span class="token punctuation">]</span><span class="token punctuation">)</span>

p2<span class="token operator">=</span>class1<span class="token punctuation">[</span><span class="token string">'hanmeimei'</span><span class="token punctuation">]</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p2<span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>p2<span class="token punctuation">[</span><span class="token string">'score'</span><span class="token punctuation">]</span><span class="token punctuation">)</span>

<span class="token keyword">print</span><span class="token punctuation">(</span>class1<span class="token punctuation">[</span><span class="token string">'lilei'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token string">'testing_class'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> class1<span class="token punctuation">[</span><span class="token string">'hanmeimei'</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token string">'score'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> sep<span class="token operator">=</span><span class="token string">','</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>输出：</p>
<p><img src="@source/1v1/03-Dannie/13.assets/image-20221107220337293.png" alt="image-20221107220337293" loading="lazy"></p>
<p>容易混淆，总结：</p>
<blockquote>
<p>提取列表里面的数值， 是 按照位置提取 ， 如 <code v-pre>list_1[2]</code> , 就是 列表里面的 2号位的数值</p>
<p>但是 提取字典里面的数值， 是提取 key</p>
</blockquote>
<p><img src="@source/1v1/03-Dannie/13.assets/image-20221107220623761.png" alt="image-20221107220623761" loading="lazy"></p>
<div class="custom-container tip">
<p class="custom-container-title">提示</p>
<p>最后一句， 如果用 <code v-pre>.get()</code> 实现。 可以这样写：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">print</span><span class="token punctuation">(</span>class1<span class="token punctuation">.</span>get<span class="token punctuation">(</span><span class="token string">'lilei'</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token string">'testing_class'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> class1<span class="token punctuation">.</span>get<span class="token punctuation">(</span><span class="token string">'hanmeimei'</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token string">'score'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> sep<span class="token operator">=</span><span class="token string">','</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>甚至可以再继续用 <code v-pre>.get()</code>  ， 可以这样写：</p>
<div class="language-python line-numbers-mode" data-ext="py"><pre v-pre class="language-python"><code><span class="token keyword">print</span><span class="token punctuation">(</span>class1<span class="token punctuation">.</span>get<span class="token punctuation">(</span><span class="token string">'lilei'</span><span class="token punctuation">)</span><span class="token punctuation">.</span>get<span class="token punctuation">(</span><span class="token string">'testing_class'</span><span class="token punctuation">)</span><span class="token punctuation">,</span> class1<span class="token punctuation">.</span>get<span class="token punctuation">(</span><span class="token string">'hanmeimei'</span><span class="token punctuation">)</span><span class="token punctuation">.</span>get<span class="token punctuation">(</span><span class="token string">'score'</span><span class="token punctuation">)</span><span class="token punctuation">,</span> sep<span class="token operator">=</span><span class="token string">','</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>得出的输出也是 ：</p>
<p><img src="@source/1v1/03-Dannie/13.assets/image-20221107221810069.png" alt="image-20221107221810069" loading="lazy"></p>
</div>
<p>欢迎关注我公众号：AI悦创，有更多更好玩的等你发现！</p>
<div class="custom-container info">
<p class="custom-container-title">AI悦创·编程一对一</p>
<p>AI悦创·推出辅导班啦，包括「Python 语言辅导班、C++ 辅导班、java 辅导班、算法/数据结构辅导班、少儿编程、pygame 游戏开发」，全部都是一对一教学：一对一辅导 + 一对一答疑 + 布置作业 + 项目实践等。当然，还有线下线上摄影课程、Photoshop、Premiere 一对一教学、QQ、微信在线，随时响应！微信：Jiabcdefh</p>
<p>C++ 信息奥赛题解，长期更新！长期招收一对一中小学信息奥赛集训，莆田、厦门地区有机会线下上门，其他地区线上。微信：Jiabcdefh</p>
<p>方法一：<a href="http://wpa.qq.com/msgrd?v=3&amp;uin=1432803776&amp;site=qq&amp;menu=yes" target="_blank" rel="noopener noreferrer">QQ<ExternalLinkIcon/></a></p>
<p>方法二：微信：Jiabcdefh</p>
</div>
</div></template>


